name: Deploy Frontend

on:
  push:
    branches:
      - main  # или другая ветка, по которой ты хочешь запускать деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "Private key:"
          echo "${{ secrets.SSH_PRIVATE_KEY }}"  # добавляем вывод ключа для проверки
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Adding host to known_hosts..."
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts  # выводим содержимое файла known_hosts для проверки

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/client  # путь к проекту на сервере
            git pull
            npm install
            npm run build
          EOF